### ISSUE TITLE
SMTP Auth Error 

### ISSUE THREAD

**Issue by karlosss** [karlosss/learnshell-issues#1]
Vytvoril jsem si uzivatele a neprisel mi email, reklo mi to toto
![screenshot_20160927_095541](https://cloud.githubusercontent.com/assets/8711362/18864893/d0ff1402-8498-11e6-809e-f668ea8406a2.png)

**Comment by xhanj02** [comment]
same here.

**Comment by karlosss** [comment]
Opraveno. Snad :)
