### ISSUE TITLE
[feature] Nové úlohy k závěrečnému testu

### ISSUE THREAD

**Issue by tajnymag** [karlosss/learnshell-issues#5]
Máte v plánu přidat ještě poslední soubor úloh ke čtvrtému PS1 testu?

**Comment by karlosss** [comment]
za me urcite ne, jedine jestli se @HoBi bude chtit...bohuzel toho mam hrozne moc, navic aspon loni byl ctvrty test tak nejak opakovanim vseho + archivace (easy, staci cist manual) + procesy (v learnshellu nejde), takze si myslim, ze jiz pritomne ulohy by jako procviceni mely stacit

**Comment by tenhobi** [comment]
Nemáme prozatím ideální možnost přidávání a udělat testování archivace a komprese a podobných "blbůstek" by zabralo dost času. Každopádně tam bude určitě opakování minulých testů; stejně jako bylo opakování předešlých znalostí i ve třetím testu.

Udělej si tedy všechny dosavadní úlohy a pročti si nějaké dokumentace k novým věcem a mělo by to snad stačit. :-)
